openapi: 3.0.2

info:
  title: Example
  version: 1.0.0

servers:
  - url: http://backend.com/path

paths:
  /params:
    get:
      x-kong-plugin-request-validator:
        enabled: true
        config:
          verbose_response: true
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
  /body:
    post:
      x-kong-plugin-request-validator:
        enabled: true
        config:
          verbose_response: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jsonSchema'
          application/xml:
            schema:
              $ref: '#/components/schemas/xmlSchema'

components:
  schemas:
    jsonSchema:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    xmlSchema:
      type: object
      properties:
        prop:
          type: integer
