import type { CreateMessageRequest, CreateMessageResult } from '@modelcontextprotocol/sdk/types.js';
import type { RJSFSchema, UiSchema } from '@rjsf/utils/lib/types.js';
import { useEffect, useRef, useState } from 'react';
import { Button, Toolbar } from 'react-aria-components';

import type { MultiTurnMessage } from '~/plugins/types';
import { useAIGenerateActionFetcher } from '~/routes/ai.mcp-generate-sampling-response';
import { Icon } from '~/ui/components/icon';
import { InsomniaRjsfForm, type InsomniaRjsfFormHandle } from '~/ui/components/rjsf';
import { useAIFeatureStatus } from '~/ui/hooks/use-organization-features';

interface SamplingFormProps {
  requestId: string;
  serverRequestId: string;
  samplingData: CreateMessageRequest;
}

const uiSchema: UiSchema = {
  'ui:submitButtonOptions': {
    norender: true,
  },
  'content': {
    'ui:widget': 'textarea',
  },
};

const samplingFormSchema: RJSFSchema = {
  type: 'object',
  properties: {
    content: {
      type: 'string',
      description: 'The content of the message generated by the LLM.',
    },
    role: {
      type: 'string',
      enum: ['user', 'assistant'],
    },
    model: {
      type: 'string',
    },
    stopReason: {
      type: 'string',
      enum: ['endTurn', 'stopSequence', 'maxTokens'],
    },
  },
  required: ['content', 'model', 'role'],
};

export const SamplingForm = ({ requestId, serverRequestId, samplingData }: SamplingFormProps) => {
  const rjsfFormRef = useRef<InsomniaRjsfFormHandle>(null);
  const [formData, setFormData] = useState({});
  const { isMCPWithAIEnabled } = useAIFeatureStatus();

  const handleRjsfFormChange = (formData: any) => {
    setFormData(formData);
  };
  const generateSamplingResponseFetcher = useAIGenerateActionFetcher();
  const isGenerating = generateSamplingResponseFetcher.state !== 'idle';

  return (
    <div className="flex flex-grow flex-col overflow-hidden">
      <div className="h-[calc(100%-var(--line-height-sm))] overflow-auto bg-inherit px-5 py-1">
        <InsomniaRjsfForm
          formData={formData}
          onChange={handleRjsfFormChange}
          schema={samplingFormSchema}
          uiSchema={uiSchema}
          ref={rjsfFormRef}
          showErrorList={false}
          focusOnFirstError
        />
      </div>
      <Toolbar className="content-box sticky bottom-0 z-10 flex h-[var(--line-height-sm)] flex-shrink-0 gap-3 border-b border-[var(--hl-md)] bg-[var(--color-bg)] px-5 py-2 text-[var(--font-size-sm)]">
        {isMCPWithAIEnabled && (
          <Button
            onPress={() => {
              const { params } = samplingData;
              const { messages, maxTokens, temperature, systemPrompt } = params;
              const samplingMessages: MultiTurnMessage[] = [];
              for (const msg of messages) {
                const { role, content } = msg;
                if (content.type === 'text') {
                  // only handle text type for now
                  samplingMessages.push({
                    role,
                    content: content.text,
                  });
                }
              }
              generateSamplingResponseFetcher.submit({
                messages: samplingMessages,
                systemPrompt,
                maxTokens,
                temperature,
                requestId,
                serverRequestId,
              });
            }}
            className="rounded-sm bg-[--color-surprise] px-[--padding-md] text-center text-[--color-font-surprise] hover:brightness-75"
          >
            <Icon
              icon={isGenerating ? 'spinner' : 'star'}
              className={`mr-1 size-4 ${isGenerating ? 'animate-spin' : ''}`}
            />
            Answer by AI
          </Button>
        )}
        <Button
          onPress={() => {
            if (rjsfFormRef.current?.validate()) {
              const samplingFormData = formData as Pick<CreateMessageResult, 'model' | 'stopReason' | 'role'> & {
                content: string;
              };
              window.main.mcp.client.responseSamplingRequest({
                requestId,
                serverRequestId,
                type: 'approve',
                result: {
                  content: {
                    type: 'text',
                    text: samplingFormData.content,
                  },
                  model: samplingFormData.model,
                  stopReason: samplingFormData.stopReason || '',
                  role: samplingFormData.role,
                },
              });
            }
          }}
          className="rounded-sm bg-[--color-surprise] px-[--padding-md] text-center text-[--color-font-surprise] hover:brightness-75"
        >
          Approve
        </Button>
        <Button
          onPress={() =>
            window.main.mcp.client.responseSamplingRequest({
              requestId,
              serverRequestId,
              type: 'reject',
              reason: 'User rejected the sampling request',
            })
          }
          className="rounded-[var(--radius-md)] border border-solid border-[var(--hl-lg)] bg-[var(--color-bg)] px-[var(--padding-md)] text-center"
        >
          Reject
        </Button>
      </Toolbar>
    </div>
  );
};
