daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - High Priority
  - Accepted
  - Help Wanted
  - Needs Discussion
  - Blocked
  - Bug
staleLabel: Stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
