image: Visual Studio 2015

build: off
deploy: off

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true
platform: x64
environment:
  NODE_ENV: development
  nodejs_version: "6.5.0"

# Things to install after repo clone
install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - npm config set msvs_version 2015
  - npm install --build-from-source

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - node --version
  - npm --version
  - npm run test

#on_success:
#  - npm run build-n-package:win
#  - ps: ls .\dist\win\* | % { Push-AppveyorArtifact $_.FullName }

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
#
#deploy:
#  - provider: S3
#    access_key_id:
#      secure: ABcd==
#    secret_access_key:
#      secure: ABcd==
#    bucket: my_bucket
#    folder:
#    artifact:
#    set_public: false
