image: Visual Studio 2015
build: off

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true
platform: x64
environment:
  nodejs_version: "7.4.0"

# Things to install after repo clone
install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - npm install -g npm@latest > Nul
  - npm install > NUL

cache:
  - '%APPDATA%\npm-cache -> .appveyor.cache'
  - '%USERPROFILE%\.electron -> .appveyor.cache'
  - 'node_modules -> .appveyor.cache'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - node --version
  - npm --version
  - npm test

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#deploy:
#  - provider: S3
#    access_key_id:
#      secure: ABcd==
#    secret_access_key:
#      secure: ABcd==
#    bucket: my_bucket
#    folder:
#    artifact:
#    set_public: false

#---------------------------------#
#         global handlers         #
#---------------------------------#

#deploy_script:
#  - npm run build-n-package:win
#  - ps: ls .\dist\win\* | % { Push-AppveyorArtifact $_.FullName }
