# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  node_version: "6.4"
  matrix:
    - platform: x64

image: Visual Studio 2015

init:
  - npm config set msvs_version 2015 # we need this to build `pty.js`

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm -g install npm@latest

build: off

shallow_clone: true

test_script:
  - SET NODE_ENV=development && npm install
  - npm test
  - npm run build-n-package:win

on_success:
  - npm run dist
  - ps: ls .\dist\win\* | % { Push-AppveyorArtifact $_.FullName }
