# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  nodejs_version: "6.5.0"
platform:
  - x64

image: Visual Studio 2015

init:
  - npm config set msvs_version 2015

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - set CI=true
  - npm -g install npm@latest

build: off

shallow_clone: true

#cache:
#  - '%APPDATA%\npm-cache'
#  - '%USERPROFILE%\.electron'

test_script:
  - node -e "console.log('Platform', process.arch, process.platform)"
  - node --version
  - npm --version
  - SET NODE_ENV=development && npm install
#  - npm test

on_success:
  - npm run build-n-package:win
  - ps: ls .\dist\win\*.exe | % { Push-AppveyorArtifact $_.FullName }
