image: Visual Studio 2015

environment:
  nodejs_version: "6.5.0"

platform: x64

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node -e "console.log(process.arch)"
  - node --version
  - npm --version
  - npm install --build-from-source git://github.com/getinsomnia/node-libcurl.git#22cbeee8179dbb7a1465007dbd62aec2d4da6112 --msvs_version=2015

#  - npm install
#  - npm test
#  - npm run build-n-package:win

shallow_clone: true

#cache:
#  - '%APPDATA%\npm-cache'
#  - '%USERPROFILE%\.electron'

build: off
test: off
deploy: off
