image: Visual Studio 2015
build: off

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true
platform: x64
environment:
  nodejs_version: "7.4.0"

# Things to install after repo clone
install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - npm install -g npm@latest > Nul
  - npm config set msvs_version 2013
  - npm install > NUL

cache:
  - '%APPDATA%\npm-cache -> .appveyor.cache'
  - '%USERPROFILE%\.electron -> .appveyor.cache'
  - 'node_modules -> .appveyor.cache'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - node --version
  - npm --version
  - npm test

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

before_deploy:
- npm run build-n-package:win

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: Ffmgxn+wt5WSf/jgJ/L+/3mkUs4fn9Z5j4Dz73VATsgL14Rf/xUp2nOyE0ecow+1
  artifact: ./dist/win/*
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
