module.exports.themes = [
  require('./themes/default'),
  require('./themes/studio-light'),
  require('./themes/studio-dark'),
  require('./themes/material'),
  require('./themes/simple-light'),
  require('./themes/simple-dark'),
  require('./themes/one-light'),
  require('./themes/one-dark'),
  require('./themes/purple'),
  require('./themes/gruvbox'),
  require('./themes/hyper'),
  require('./themes/railscasts'),
  require('./themes/solarized-light'),
  require('./themes/solarized'),
  require('./themes/solarized-dark'),
  require('./themes/high-contrast-light'),
  require('./themes/dark-colorblind')
];
