export const themesFn = async () => [
  (await import('./themes/default')).default,
  (await import('./themes/legacy')).default,
  (await import('./themes/studio-light')).default,
  (await import('./themes/studio-dark')).default,
  (await import('./themes/material')).default,
  (await import('./themes/simple-light')).default,
  (await import('./themes/simple-dark')).default,
  (await import('./themes/one-light')).default,
  (await import('./themes/one-dark')).default,
  (await import('./themes/purple')).default,
  (await import('./themes/gruvbox')).default,
  (await import('./themes/hyper')).default,
  (await import('./themes/railscasts')).default,
  (await import('./themes/solarized-light')).default,
  (await import('./themes/solarized')).default,
  (await import('./themes/solarized-dark')).default,
  (await import('./themes/high-contrast-light')).default,
  (await import('./themes/colorblind-dark')).default,
];
