import type { AllTypes, BaseModel } from '~/insomnia-data';
import { models } from '~/insomnia-data';

export type { AllTypes, BaseModel };
// Reference to each model
export const apiSpec = models.apiSpec;
export const clientCertificate = models.clientCertificate;
export const caCertificate = models.caCertificate;
export const cookieJar = models.cookieJar;
export const environment = models.environment;
export const gitCredentials = models.gitCredentials;
export const gitRepository = models.gitRepository;
export const oAuth2Token = models.oAuth2Token;
export const pluginData = models.pluginData;
export const mockServer = models.mockServer;
export const mockRoute = models.mockRoute;
export const request = models.request;
export const requestGroup = models.requestGroup;
export const requestGroupMeta = models.requestGroupMeta;
export const requestMeta = models.requestMeta;
export const requestVersion = models.requestVersion;
export const runnerTestResult = models.runnerTestResult;
export const response = models.response;
export const settings = models.settings;
export const project = models.project;
export const stats = models.stats;
export const unitTest = models.unitTest;
export const unitTestSuite = models.unitTestSuite;
export const unitTestResult = models.unitTestResult;
export const protoFile = models.protoFile;
export const protoDirectory = models.protoDirectory;
export const grpcRequest = models.grpcRequest;
export const grpcRequestMeta = models.grpcRequestMeta;
export const workspace = models.workspace;
export const workspaceMeta = models.workspaceMeta;
export const webSocketPayload = models.webSocketPayload;
export const webSocketRequest = models.webSocketRequest;
export const webSocketResponse = models.webSocketResponse;
export const socketIORequest = models.socketIORequest;
export const socketIOPayload = models.socketIOPayload;
export const socketIOResponse = models.socketIOResponse;
export const userSession = models.userSession;
export const cloudCredential = models.cloudCredential;
export const mcpRequest = models.mcpRequest;
export const mcpPayload = models.mcpPayload;
export const mcpResponse = models.mcpResponse;
export const organization = models.organization;

export const all = models.all;
export const types = models.types;
export const isValidType = models.isValidType;
export const canSync = models.canSync;
export const getAllDescendantMap = models.getAllDescendantMap;
export const generateDescendantMap = models.generateDescendantMap;
export const getModel = models.getModel;
export const rewriteReferences = models.rewriteReferences;
export const canDuplicate = models.canDuplicate;
export const mustGetModel = models.mustGetModel;
