import { CONTENT_TYPE_JSON } from '~/common/constants';
import { newDefaultRegistry } from '~/common/hotkeys';
import { HttpVersions, UpdateChannel } from '~/common/settings';
import { TRANSPORT_TYPES } from '~/models/mcp-request';

import appConfig from '../../config/config.json';
// TODO: come up with a meta sort key flag so its set at creation time
export const databaseSchema = {
  apiSpec: {
    name: 'ApiSpec',
    type: 'ApiSpec',
    prefix: 'spc',
    canDuplicate: true,
    canSync: true,
    defaults: {
      fileName: `New Document`,
      contents: '',
      contentType: 'yaml',
    },
  },
  caCertificate: {
    name: 'CaCertificate',
    type: 'CaCertificate',
    prefix: 'crt',
    canDuplicate: true,
    canSync: false,
    defaults: {
      parentId: '',
      disabled: false,
      path: null,
      isPrivate: false,
    },
  },
  clientCertificate: {
    name: 'ClientCertificate',
    type: 'ClientCertificate',
    prefix: 'crt',
    canDuplicate: true,
    canSync: false,
    defaults: {
      parentId: '',
      host: '',
      passphrase: null,
      disabled: false,
      cert: null,
      key: null,
      pfx: null,
      isPrivate: false,
    },
  },
  cloudCredential: {
    name: 'Cloud Credential',
    type: 'CloudCredential',
    prefix: 'cloudCred',
    canDuplicate: false,
    canSync: false,
    defaults: {
      name: '',
      provider: undefined,
      credentials: undefined,
    },
  },
  cookieJar: {
    name: 'Cookie Jar',
    type: 'CookieJar',
    prefix: 'jar',
    canDuplicate: true,
    canSync: false,
    defaults: {
      name: 'Default Jar',
      cookies: [],
    },
  },
  environment: {
    name: 'Environment',
    type: 'Environment',
    prefix: 'env',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'New Environment',
      data: {},
      dataPropertyOrder: null,
      color: null,
      isPrivate: false,
      metaSortKey: Date.now(),
    },
    optionalKeys: ['kvPairData', 'environmentType'],
  },
  gitCredentials: {
    name: 'Git Credentials',
    type: 'GitCredentials',
    prefix: 'git_creds',
    canDuplicate: false,
    canSync: false,
    defaults: {
      token: '',
      refreshToken: '',
      provider: 'github',
      author: {
        email: '',
        name: '',
        avatarUrl: '',
      },
    },
  },
  gitRepository: {
    name: 'Git Repository',
    type: 'GitRepository',
    prefix: 'git',
    canDuplicate: false,
    canSync: false,
    defaults: {
      needsFullClone: false,
      uri: '',
      credentials: null,
      author: {
        name: '',
        email: '',
      },
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      cachedGitLastAuthor: null,
      hasUncommittedChanges: false,
      hasUnpushedChanges: false,
      uriNeedsMigration: true,
    },
  },
  grpcRequest: {
    name: 'gRPC Request',
    type: 'GrpcRequest',
    prefix: 'greq',
    canDuplicate: true,
    canSync: true,
    defaults: {
      url: '',
      name: 'New gRPC Request',
      description: '',
      protoFileId: '',
      protoMethodName: '',
      metadata: [],
      body: {
        text: '{}',
      },
      metaSortKey: -1 * Date.now(),
      isPrivate: false,
      reflectionApi: {
        enabled: false,
        url: 'https://buf.build',
        apiKey: '',
        module: 'buf.build/connectrpc/eliza',
      },
    },
  },
  grpcRequestMeta: {
    name: 'gRPC Request Meta',
    type: 'GrpcRequestMeta',
    prefix: 'greqm',
    canDuplicate: false,
    canSync: false,
    defaults: {
      pinned: false,
      lastActive: 0,
    },
  },
  mcpPayload: {
    name: 'MCP Payload',
    type: 'McpPayload',
    prefix: 'mcp-payload',
    canDuplicate: true,
    canSync: false,
    defaults: {
      params: {},
      url: '',
    },
  },
  mcpRequest: {
    name: 'McpRequest',
    type: 'McpRequest',
    prefix: 'mcp-request',
    canDuplicate: false,
    canSync: false,
    defaults: {
      url: '',
      transportType: TRANSPORT_TYPES.HTTP,
      name: 'New MCP Client',
      description: '',
      headers: [],
      authentication: {},
      env: [],
      mcpStdioAccess: false,
      roots: [],
      subscribeResources: [],
      connected: false,
      sslValidation: true,
    },
  },
  mcpResponse: {
    name: 'Mcp Response',
    type: 'McpResponse',
    prefix: 'mcp-response',
    canDuplicate: false,
    canSync: false,
    defaults: {
      url: '',
      elapsedTime: 0,
      headers: [],
      timelinePath: '',
      eventLogPath: '',
      error: '',
      errorType: '',
      status: '',
      statusCode: 0,
      statusMessage: '',
      requestVersionId: null,
      environmentId: null,
      transportType: TRANSPORT_TYPES.HTTP,
    },
  },
  mockRoute: {
    name: 'Mock Route',
    type: 'MockRoute',
    prefix: 'mock-route',
    canDuplicate: true,
    canSync: true,
    defaults: {
      body: '',
      headers: [],
      parentId: '',
      statusCode: 200,
      statusText: '',
      name: '/',
      mimeType: 'application/json',
      method: 'GET',
    },
  },
  mockServer: {
    name: 'Mock Server',
    type: 'MockServer',
    prefix: 'mock',
    canDuplicate: true,
    canSync: true,
    defaults: {
      parentId: '',
      name: 'New Mock',
      url: 'http://localhost:8080',
      useInsomniaCloud: true,
    },
  },
  oauth2Token: {
    name: 'OAuth 2.0 Token',
    type: 'OAuth2Token',
    prefix: 'oa2',
    canDuplicate: false,
    canSync: false,
    defaults: {
      parentId: '',
      refreshToken: '',
      accessToken: '',
      identityToken: '',
      expiresAt: null,
      xResponseId: null,
      xError: null,
      error: '',
      errorDescription: '',
      errorUri: '',
    },
  },
  pluginData: {
    name: 'PluginData',
    type: 'PluginData',
    prefix: 'plg',
    canDuplicate: false,
    canSync: false,
    defaults: {
      plugin: '',
      key: '',
      value: '',
    },
  },
  project: {
    name: 'Project',
    type: 'Project',
    prefix: 'proj',
    canDuplicate: false,
    canSync: false,
    defaults: {
      name: 'My Project',
      remoteId: null, // `null` is necessary for the model init logic to work properly
      gitRepositoryId: null,
      mcpStdioAccess: false,
    },
  },
  protoDirectory: {
    name: 'Proto Directory',
    type: 'ProtoDirectory',
    prefix: 'pd',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'New Proto Directory',
    },
  },
  protoFile: {
    name: 'Proto File',
    type: 'ProtoFile',
    prefix: 'pf',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'New Proto File',
      protoText: '',
    },
  },
  request: {
    name: 'Request',
    type: 'Request',
    prefix: 'req',
    canDuplicate: true,
    canSync: true,
    defaults: {
      url: '',
      name: 'New Request',
      description: '',
      method: 'GET',
      body: {},
      parameters: [],
      headers: [],
      authentication: {},
      preRequestScript: undefined,
      metaSortKey: -1 * Date.now(),
      isPrivate: false,
      pathParameters: undefined,
      afterResponseScript: undefined,
      // Settings
      settingStoreCookies: true,
      settingSendCookies: true,
      settingDisableRenderRequestBody: false,
      settingEncodeUrl: true,
      settingRebuildPath: true,
      settingFollowRedirects: 'global',
    },
  },
  requestGroup: {
    name: 'Folder',
    type: 'RequestGroup',
    prefix: 'fld',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'New Folder',
      description: '',
      environment: {},
      environmentPropertyOrder: null,
      metaSortKey: -1 * Date.now(),
      preRequestScript: undefined,
      afterResponseScript: undefined,
      authentication: undefined,
      headers: undefined,
    },
    optionalKeys: ['kvPairData', 'environmentType'],
  },
  requestGroupMeta: {
    name: 'Folder Meta',
    type: 'RequestGroupMeta',
    prefix: 'fldm',
    canDuplicate: false,
    canSync: false,
    defaults: {
      parentId: null,
      collapsed: false,
    },
  },
  requestMeta: {
    name: 'RequestMeta',
    type: 'RequestMeta',
    prefix: 'reqm',
    canDuplicate: false,
    canSync: false,
    defaults: {
      pinned: false,
      lastActive: 0,
      parentId: null,
      previewMode: 'friendly',
      responseFilter: '',
      responseFilterHistory: [],
      activeResponseId: null,
      savedRequestBody: {},
      downloadPath: null,
      expandedAccordionKeys: {},
    },
  },
  requestVersion: {
    name: 'Request Version',
    type: 'RequestVersion',
    prefix: 'rvr',
    canDuplicate: false,
    canSync: false,
    defaults: {
      compressedRequest: null,
    },
  },
  response: {
    name: 'Response',
    type: 'Response',
    prefix: 'res',
    canDuplicate: false,
    canSync: false,
    defaults: {
      statusCode: 0,
      statusMessage: '',
      httpVersion: '',
      contentType: '',
      url: '',
      bytesRead: 0,
      // -1 means that it was legacy and this property didn't exist yet
      bytesContent: -1,
      elapsedTime: 0,
      headers: [],
      // Actual timelines are stored on the filesystem
      timelinePath: '',
      // Actual bodies are stored on the filesystem
      bodyPath: '',
      // For legacy bodies
      bodyCompression: '__NEEDS_MIGRATION__',
      error: '',
      // Things from the request
      requestVersionId: null,
      settingStoreCookies: null,
      settingSendCookies: null,
      // Responses sent before environment filtering will have a special value
      // so they don't show up at all when filtering is on.
      environmentId: '__LEGACY__',
      requestTestResults: [],
      globalEnvironmentId: null,
    },
  },
  runnerTestResult: {
    name: 'Runner Test Result',
    type: 'RunnerTestResult',
    prefix: 'rtr',
    canDuplicate: false,
    canSync: false,
    defaults: {
      source: 'runner',
      iterations: 0,
      duration: 0,
      avgRespTime: 0,
      iterationResults: [],
      responsesInfo: [],
      version: '1',
    },
  },
  settings: {
    name: 'Settings',
    type: 'Settings',
    prefix: 'set',
    canDuplicate: false,
    canSync: false,
    defaults: {
      autoDetectColorScheme: false,
      autoHideMenuBar: false,
      autocompleteDelay: 1200,
      clearOAuth2SessionOnRestart: true,
      darkTheme: appConfig.darkTheme,
      deviceId: null,
      disableHtmlPreviewJs: false,
      disableResponsePreviewLinks: false,
      disableAppVersionUserAgent: false,
      disableUpdateNotification: false,
      editorFontSize: 11,
      editorIndentSize: 2,
      editorIndentWithTabs: true,
      editorKeyMap: 'default',
      enableKeyMapForInlineTextEditors: false,
      editorLineWrapping: true,
      enableAnalytics: true,
      showVariableSourceAndValue: false,
      filterResponsesByEnv: false,
      followRedirects: true,
      fontInterface: null,
      fontMonospace: null,
      fontSize: 13,
      fontVariantLigatures: false,
      forceVerticalLayout: !!process.env.PLAYWRIGHT,
      hotKeyRegistry: newDefaultRegistry(),
      httpProxy: '',
      httpsProxy: '',
      lightTheme: appConfig.lightTheme,
      maxHistoryResponses: 20,
      maxRedirects: 10,
      maxTimelineDataSizeKB: 10,
      pluginNodeExtraCerts: '',
      pluginsAllowElevatedAccess: false,
      noProxy: '',
      nunjucksPowerUserMode: false,
      pluginConfig: {},
      pluginPath: '',
      preferredHttpVersion: HttpVersions.default,
      proxyEnabled: false,
      showPasswords: false,
      theme: appConfig.theme,
      // milliseconds
      timeout: 30_000,
      updateAutomatically: true,
      updateChannel: UpdateChannel.stable,
      useBulkHeaderEditor: false,
      useBulkParametersEditor: false,
      validateAuthSSL: true,
      validateSSL: true,
      saveVaultKeyLocally: true,
      enableVaultInScripts: false,
      saveVaultKeyToOSSecretManager: true,
      // The duration in mins for which the external vault secret is cached
      vaultSecretCacheDuration: 30,
      dataFolders: [],
    },
  },
  socketIOPayload: {
    name: 'SocketIO Payload',
    type: 'SocketIOPayload',
    prefix: 'socket-io-payload',
    canDuplicate: true,
    canSync: true,
    defaults: {
      args: [{ id: crypto.randomUUID(), value: '', mode: CONTENT_TYPE_JSON }],
      eventName: '',
      ack: false,
    },
  },
  socketIORequest: {
    name: 'Socket.IO Request',
    type: 'SocketIORequest',
    prefix: 'socketio-req',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'New Socket.IO Request',
      url: '',
      metaSortKey: -1 * Date.now(),
      headers: [],
      authentication: {},
      parameters: [],
      pathParameters: undefined,
      settingEncodeUrl: true,
      settingStoreCookies: true,
      settingSendCookies: true,
      description: '',
      eventListeners: [],
    },
  },
  socketIOResponse: {
    name: 'SocketIO Response',
    type: 'SocketIOResponse',
    prefix: 'socketIO-res',
    canDuplicate: false,
    canSync: false,
    defaults: {
      timelinePath: '',
      eventLogPath: '',
      requestVersionId: null,
      environmentId: null,
      elapsedTime: 0,
      error: '',
      url: '',
    },
  },
  stats: {
    name: 'Stats',
    type: 'Stats',
    prefix: 'sta',
    canDuplicate: false,
    canSync: false,
    defaults: {
      currentLaunch: null,
      lastLaunch: null,
      currentVersion: null,
      lastVersion: null,
      launches: 0,
      createdRequests: 0,
      deletedRequests: 0,
      executedRequests: 0,
    },
  },
  unitTest: {
    name: 'UnitTest',
    type: 'UnitTest',
    prefix: 'ut',
    canDuplicate: true,
    canSync: true,
    defaults: {
      requestId: null,
      name: 'My Test',
      code: '',
      metaSortKey: -1 * Date.now(),
    },
  },
  unitTestSuite: {
    name: 'Unit Test Suite',
    type: 'UnitTestSuite',
    prefix: 'uts',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'My Test',
      metaSortKey: -1 * Date.now(),
    },
  },
  unitTestResult: {
    name: 'Unit Test Result',
    type: 'UnitTestResult',
    prefix: 'utr',
    canDuplicate: false,
    canSync: false,
    defaults: {
      results: null,
    },
  },
  userSession: {
    name: 'UserSession',
    type: 'UserSession',
    prefix: 'us',
    canDuplicate: false,
    canSync: false,
    defaults: {
      accountId: '',
      id: '',
      email: '',
      firstName: '',
      lastName: '',
      symmetricKey: {},
      publicKey: {},
      encPrivateKey: {},
      vaultKey: '',
      vaultSalt: '',
    },
  },
  webSocketPayload: {
    name: 'WebSocket Payload',
    type: 'WebSocketPayload',
    prefix: 'ws-payload',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'New Payload',
      value: '',
      mode: 'application/json',
    },
  },
  webSocketRequest: {
    name: 'WebSocket Request',
    type: 'WebSocketRequest',
    prefix: 'ws-req',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: 'New WebSocket Request',
      url: '',
      metaSortKey: -1 * Date.now(),
      headers: [],
      authentication: {},
      parameters: [],
      pathParameters: undefined,
      settingEncodeUrl: true,
      settingStoreCookies: true,
      settingSendCookies: true,
      settingFollowRedirects: 'global',
      description: '',
    },
    optionalKeys: ['settingUseProxy'],
  },
  webSocketResponse: {
    name: 'WebSocket Response',
    type: 'WebSocketResponse',
    prefix: 'ws-res',
    canDuplicate: false,
    canSync: false,
    defaults: {
      statusCode: 0,
      statusMessage: '',
      httpVersion: '',
      contentType: '',
      url: '',
      elapsedTime: 0,
      headers: [],
      timelinePath: '',
      eventLogPath: '',
      error: '',
      requestVersionId: null,
      settingStoreCookies: null,
      settingSendCookies: null,
      environmentId: null,
    },
  },
  workspace: {
    name: 'Workspace',
    type: 'Workspace',
    prefix: 'wrk',
    canDuplicate: true,
    canSync: true,
    defaults: {
      name: `New Workspace`,
      description: '',
      scope: 'collection',
    },
  },
  workspaceMeta: {
    name: 'Workspace Meta',
    type: 'WorkspaceMeta',
    prefix: 'wrkm',
    canDuplicate: false,
    canSync: false,
    defaults: {
      activeActivity: null,
      activeEnvironmentId: null,
      activeGlobalEnvironmentId: null,
      activeRequestId: null,
      activeUnitTestSuiteId: null,
      gitRepositoryId: null,
      gitFilePath: null,
      parentId: null,
      pushSnapshotOnInitialize: false,
      hasUncommittedChanges: false,
      hasUnpushedChanges: false,
    },
  },
} as const satisfies Record<string, SchemaEntry<string>>;
interface SchemaEntry<K extends string> {
  name: string;
  type: K;
  prefix: string;
  canDuplicate: boolean;
  canSync: boolean;
  defaults: Record<string, any>;
  optionalKeys?: string[];
}
