// Global
export const GLOBAL_LOAD_START = 'GLOBAL.LOAD_START';
export const GLOBAL_LOAD_STOP = 'GLOBAL.LOAD_STOP';
export const GLOBAL_STATE_SAVED = 'GLOBAL.STATE_SAVED';
export const GLOBAL_STATE_RESTORED = 'GLOBAL.STATE_RESTORED';

// Requests
export const REQUEST_ADD = 'REQUEST.ADD';
export const REQUEST_UPDATE = 'REQUEST.UPDATE';
export const REQUEST_DELETE = 'REQUEST.DELETE';
export const REQUEST_ACTIVATE = 'REQUEST.ACTIVATE';
export const REQUEST_CHANGE_FILTER = 'REQUEST.CHANGE_FILTER';

// RequestGroups
export const REQUEST_GROUP_ADD = 'REQUEST_GROUP.ADD';
export const REQUEST_GROUP_UPDATE = 'REQUEST_GROUP.UPDATE';
export const REQUEST_GROUP_DELETE = 'REQUEST_GROUP.DELETE';
export const REQUEST_GROUP_TOGGLE = 'REQUEST_GROUP.TOGGLE';
