/**
 * Generates the vendored sandbox-module factory sources (sandbox plan M3).
 *
 * Each "vetted" npm library is bundled once, here, into a single CJS string and written to
 * `src/templating/sandbox/vendored/<name>.generated.ts` as a factory-source string the QuickJS
 * module registry can register. The generated files are checked in (reviewable, deterministic) and
 * regenerated with `npm run generate:sandbox-vendored -w insomnia` whenever a pinned version bumps.
 *
 * "Add a vetted lib" checklist:
 *   1. Add the dependency (pinned) to packages/insomnia/package.json.
 *   2. Add an entry to VENDORED_LIBS below (name + entry expression).
 *   3. Run `npm run generate:sandbox-vendored -w insomnia`.
 *   4. Register it in module-registry.ts SANDBOX_MODULES with `heavy: true`.
 *   5. Add a parity unit test (per-lib smoke) + an e2e row, and document it in PERMISSIONS.md.
 */
import fs from 'node:fs';
import path from 'node:path';

import { build } from 'esbuild';

const INSOMNIA_ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(INSOMNIA_ROOT, 'src', 'templating', 'sandbox', 'vendored');

// name → the CJS entry that re-exports the library's public surface.
const VENDORED_LIBS: { name: string; entry: string }[] = [
  { name: 'uuid', entry: "module.exports = require('uuid');" },
  { name: 'ajv', entry: "module.exports = require('ajv').default || require('ajv');" },
];

const installedVersion = (lib: string): string => {
  const pkg = require(`${lib}/package.json`) as { version: string };
  return pkg.version;
};

const bundleLib = async (entry: string): Promise<string> => {
  const result = await build({
    stdin: { contents: entry, resolveDir: INSOMNIA_ROOT, loader: 'js' },
    bundle: true,
    format: 'cjs',
    platform: 'browser', // pick browser conditionals (e.g. uuid → crypto.getRandomValues, which M2 provides)
    target: 'es2020', // classic QuickJS supports ~es2020
    define: { 'process.env.NODE_ENV': '"production"' },
    legalComments: 'none',
    write: false,
  });
  return result.outputFiles[0].text;
};

/** Wrap a CJS bundle as a factory-source string: a function that runs the module and returns exports. */
const toFactorySource = (bundle: string): string =>
  [
    'function () {',
    '  var module = { exports: {} };',
    '  var exports = module.exports;',
    '  (function (module, exports) {',
    bundle,
    '  })(module, exports);',
    '  return module.exports;',
    '}',
  ].join('\n');

const main = async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const { name, entry } of VENDORED_LIBS) {
    const version = installedVersion(name);
    const bundle = await bundleLib(entry);
    const factorySource = toFactorySource(bundle);
    const constName = `${name.toUpperCase()}_FACTORY`;
    const file = [
      `// @generated by scripts/generate-sandbox-vendored.ts — DO NOT EDIT BY HAND.`,
      `// Vendored, pinned bundle of "${name}" for the QuickJS template-tag sandbox (M3).`,
      `// Regenerate with: npm run generate:sandbox-vendored -w insomnia`,
      `/* eslint-disable */`,
      `export const ${constName}_VERSION = ${JSON.stringify(version)};`,
      `export const ${constName}_SOURCE = ${JSON.stringify(factorySource)};`,
      ``,
    ].join('\n');
    const outPath = path.join(OUT_DIR, `${name}.generated.ts`);
    fs.writeFileSync(outPath, file);
    console.log(`[vendored] ${name}@${version} → ${path.relative(INSOMNIA_ROOT, outPath)} (${bundle.length} bytes)`);
  }
};

main().catch(err => {
  console.error(err);
  process.exit(1);
});
