/**
 * Shared bundling logic for the sandbox-vendored npm libraries (M3), used by both
 * `generate-sandbox-vendored.ts` (batch/CI regeneration) and `upgrade-sandbox-vendored.ts`
 * (single-lib version bump). Single source of truth for the esbuild config and factory-wrapping so
 * the two scripts can't drift apart.
 *
 * Every vetted lib is sourced from the isolated, exact-pinned install at `PKG_DIR` — never from the
 * app's ambient `node_modules` — so the sandbox's vetted version is independent of whatever the rest
 * of the app happens to have installed. See `PKG_DIR/package.json` for the invariant this depends on.
 */
import fs from 'node:fs';
import path from 'node:path';

import { build } from 'esbuild';

export const INSOMNIA_ROOT = path.resolve(__dirname, '..');
export const OUT_DIR = path.join(INSOMNIA_ROOT, 'src', 'templating', 'sandbox', 'vendored');
export const PKG_DIR = path.join(OUT_DIR, 'pkg');

export interface VendoredLib {
  name: string;
  /** The CJS entry that re-exports the library's public surface. */
  entry: string;
}

// Resolves relative to PKG_DIR's own node_modules (the isolated install), not this script's.
const requireFromPkgDir = <T>(specifier: string): T => require(require.resolve(specifier, { paths: [PKG_DIR] })) as T;

/** The exact, installed version of a vetted lib in the isolated install — never the ambient one. */
export const installedVersion = (lib: string): string => {
  const nodeModulesDir = path.join(PKG_DIR, 'node_modules', lib);
  if (!fs.existsSync(nodeModulesDir)) {
    throw new Error(
      `Sandbox-vendored lib '${lib}' isn't installed in the isolated pkg. Run:\n` +
      `  npm ci --prefix ${path.relative(INSOMNIA_ROOT, PKG_DIR)}\n` +
      `first, then re-run this script.`,
    );
  }
  const pkg = requireFromPkgDir<{ version: string }>(`${lib}/package.json`);
  return pkg.version;
};

export const bundleLib = async (entry: string): Promise<string> => {
  const result = await build({
    stdin: { contents: entry, resolveDir: PKG_DIR, loader: 'js' },
    bundle: true,
    format: 'cjs',
    platform: 'browser', // pick browser conditionals (e.g. uuid → crypto.getRandomValues, which M2 provides)
    target: 'es2020', // classic QuickJS supports ~es2020
    define: { 'process.env.NODE_ENV': '"production"' },
    legalComments: 'none',
    write: false,
  });
  return result.outputFiles[0].text;
};

/** Wrap a CJS bundle as a factory-source string: a function that runs the module and returns exports. */
export const toFactorySource = (bundle: string): string =>
  ['function () {', '  var module = { exports: {} };', '  var exports = module.exports;', '  (function (module, exports) {', bundle, '  })(module, exports);', '  return module.exports;', '}'].join('\n');

/** Bundle one vetted lib and write its `<name>.generated.ts` file. Returns the version that was baked in. */
export const generateVendoredFile = async ({ name, entry }: VendoredLib): Promise<string> => {
  const version = installedVersion(name);
  const bundle = await bundleLib(entry);
  const factorySource = toFactorySource(bundle);
  const constName = `${name.toUpperCase()}_FACTORY`;
  const file = [
    `// @generated by scripts/generate-sandbox-vendored.ts — DO NOT EDIT BY HAND.`,
    `// Vendored, pinned bundle of "${name}" for the QuickJS template-tag sandbox (M3).`,
    `// Sourced from the isolated install in vendored/pkg/ (see its package.json) — NOT the app's own node_modules.`,
    `// Regenerate with: npm run sandbox:vendored:generate -w insomnia`,
    `/* eslint-disable */`,
    `export const ${constName}_VERSION = ${JSON.stringify(version)};`,
    `export const ${constName}_SOURCE = ${JSON.stringify(factorySource)};`,
    ``,
  ].join('\n');
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const outPath = path.join(OUT_DIR, `${name}.generated.ts`);
  fs.writeFileSync(outPath, file);
  console.log(`[vendored] ${name}@${version} → ${path.relative(INSOMNIA_ROOT, outPath)} (${bundle.length} bytes)`);
  return version;
};
