#!/bin/bash
#? Package the app

echo "-- REMOVING DIST FOLDER --"
rm -r dist/*

echo "-- BUILDING PRODUCTION APP --"
NODE_ENV=production node -r babel-register ./node_modules/.bin/webpack --config ./webpack/webpack.config.production.js

echo "-- COPYING REMAINING FILES --"

cp -r app/package.json app/app.js app/external dist/

echo "-- INSTALLING PACKAGES --"

cp -r app/node_modules dist/
# cd dist/; NODE_ENV=production npm install; cd ..

echo "-- PACKAGING APP --"

node -r babel-register node_modules/electron-packager/cli.js \
    dist \
    Insomnia \
    --platform=darwin \
    --arch=x64 \
    --out=builds \
    --overwrite

