#!/bin/bash
#? Package the app

rm -r dist/*
webpack --config webpack/webpack.config.production.js
# cp -r node_modules electron.js package.json dist/
cp electron.js package.json dist/
cd dist
NODE_ENV=production npm install
