language: node_js

node_js:
 - iojs
 - 0.10
 - 0.12

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --yes python3 php5-curl php5-cli

after_script:
  - npm run codeclimate

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/95c4e911f2486588f98c
    on_success: always
    on_failure: always
    on_start: false
