// Single source of truth for which (serviceName, methodName) pairs have their own
// `services.<serviceName>.<methodName>` IPC handler instead of routing through the generic
// `services.invoke` gateway (see services-invoke-surface.ts, SERVICES-INVOKE-MIGRATION-PLAN.md).
// Consulted by both the preload bridge and the non-isolated renderer proxy fallback so the two
// transports can never pick a different channel for the same pair. No Node-only imports here — this
// module is bundled into the renderer as well as the main process.
export const MIGRATED_SERVICES_INVOKE_PAIRS: ReadonlySet<string> = new Set<string>([
  'caCertificate.create',
  'caCertificate.getById',
  'caCertificate.getByParentId',
  'caCertificate.removeWhere',
  'caCertificate.update',
  'clientCertificate.create',
  'clientCertificate.findByParentId',
  'clientCertificate.getById',
  'clientCertificate.remove',
  'clientCertificate.update',
  'cloudCredential.all',
  'cloudCredential.create',
  'cloudCredential.getById',
  'cloudCredential.getByName',
  'cloudCredential.remove',
  'cloudCredential.update',
  'settings.get',
  'settings.getOrCreate',
  'settings.patch',
  'settings.update',
  'gitCredentials.all',
  'gitCredentials.create',
  'gitCredentials.getById',
  'gitCredentials.remove',
  'gitCredentials.removeAll',
  'gitCredentials.update',
  'userSession.get',
  'userSession.remove',
  'userSession.update',
  'environment.create',
  'environment.update',
  'environment.list',
  'environment.listByParentId',
  'environment.getOrCreateForParentId',
  'environment.getById',
  'environment.getByParentId',
  'environment.duplicate',
  'environment.remove',
  'environment.removeAllSecrets',
  'apiSpec.getByParentId',
  'apiSpec.getOrCreateForParentId',
  'apiSpec.update',
  'apiSpec.updateOrCreateForParentId',
  'cookieJar.getById',
  'cookieJar.getOrCreateForParentId',
  'cookieJar.update',
  'gitRepository.all',
  'gitRepository.getAllByCredentialId',
  'gitRepository.getById',
  'gitRepository.remove',
  'gitRepository.update',
  'grpcRequest.create',
  'grpcRequest.findByProtoFileId',
  'grpcRequestMeta.getByParentId',
  'grpcRequestMeta.updateOrCreateByParentId',
  'helpers.abortCommandSearch',
  'helpers.commandSearch',
  'helpers.duplicateRequest',
  'helpers.findRequestByParentId',
  'helpers.getRequestById',
  'helpers.getResponseBodyBuffer',
  'helpers.getResponseTimeline',
  'helpers.queryAllWorkspaceUrls',
  'helpers.readCurlResponse',
  'helpers.removeRequest',
  'helpers.removeResponse',
  'helpers.removeResponsesForRequest',
  'helpers.updateRequest',
]);

/** The IPC channel a `services.<serviceName>.<methodName>` call should use: the named channel once migrated, else the legacy generic gateway. */
export const resolveServicesInvokeChannel = (serviceName: string, methodName: string): string =>
  MIGRATED_SERVICES_INVOKE_PAIRS.has(`${serviceName}.${methodName}`)
    ? `services.${serviceName}.${methodName}`
    : 'services.invoke';
