name: CE-Release-trigger
run-name: Trigger CE Release (${{ github.event.inputs.version}}) by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      channel:
        required: true
        type: choice
        description: Channel of the release (alpha/beta/stable)
        options:
          - alpha
          - beta
          - stable
      version:
        required: false
        description: force version of the release (e.g. 9.0.0) if previous release was successful, this should auto increment

env:
  RELEASE_VERSION: ${{ github.event.inputs.version }}
  RELEASE_BRANCH: release/${{ github.event.inputs.version }}
  ARTIFACTS_DOWNLOAD_PATH: ${{ github.workspace }}/artifacts

jobs:
  create-pr:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Create Pull Request in CE
        run: |
          gh pr create \
          --base develop \
          --head ${{ env.RELEASE_BRANCH }} \
          --title ":rocket: ${{ env.RELEASE_VERSION}}" \
          --repo kong/insomnia \
          --body "$(cat <<EOF
          # WARNING: <ins>Do not merge</ins> this PR. Use the "Publish" workflow.

          ## Publish workflow:

          When ready to publish, trigger [Publish](https://github.com/Kong/insomnia/actions/workflows/release-publish.yml) workflow with these variables:
          - Release version (\`version\`): \`${{ env.RELEASE_VERSION}}\`

          Alternatively, you can trigger the workflow from [GitHub CLI](https://cli.github.com/):
          \`\`\`bash
          gh workflow run release-publish.yml -f version=${{ env.RELEASE_VERSION}} --repo Kong/insomnia
          \`\`\`

          > Release notes will be generated automatically based on the commit messages during publish. Remove any unwanted notes manually afterwards.

          <details>
          <summary>Merge branch step failed on the publish workflow? Try this...</summary>

          Run locally:

          \`\`\`bash
          # Make sure git remote is Kong/insomnia...

          git checkout develop
          git merge --no-ff release/${{ env.RELEASE_VERSION}}

          # Solve merge conflicts ...
          # If there's package-lock conflicts, run \`npm install\` and commit the package-lock changes

          git push
          \`\`\`
          </details>
          EOF
          )"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}

  trigger-release-build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          repository: kong/insomnia
          persist-credentials: false

      - name: Configure Git user
        id: configure_git_user
        uses: Homebrew/actions/git-user-config@266845213695c3047d210b2e8fbc42ecdaf45802 # master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'insomnia-infra' }}

      - name: Git Commit
        run: git commit -am "Trigger release/${{ env.RELEASE_VERSION}} build" --allow-empty

      - name: Git Push changes
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/kong/insomnia.git"
          git push "${remote_repo}" --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
      


