name: CE-Release-trigger
run-name: Trigger CE Release (${{ github.event.inputs.version}}) by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      channel:
        required: true
        type: choice
        description: Channel of the release (alpha/beta/stable)
        options:
          - alpha
          - beta
          - stable
      version:
        required: false
        description: force version of the release (e.g. 9.0.0) if previous release was successful, this should auto increment

env:
  RELEASE_VERSION: ${{ github.event.inputs.version }}
  RELEASE_BRANCH: release/${{ github.event.inputs.version }}
  RELEASE_CHANNEL: ${{ github.event.inputs.channel }}

jobs:
  start-release:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Start Release
        run: |
          gh workflow run release-start.yml -f channel=${{ env.RELEASE_CHANNEL }} -f version=${{ env.RELEASE_VERSION }} --repo Kong/insomnia
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
      - name: Wait for Release to complete
        run: sleep 60 # wait for a minute to ensure the run is created
      - name: Get latest run ID from Kong/insomnia
        run: |
          RUN_ID=$(gh run list --repo Kong/insomnia --workflow "Release Start" --limit 1 --json databaseId -q '.[0].databaseId')
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV
          echo "Triggered run ID: $RUN_ID"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
      - name: Wait for completion
        run: |
          gh run watch ${{ env.RUN_ID }} --repo Kong/insomnia
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}

  create-pr:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: [start-release]
    steps:
      - name: Create Pull Request in CE
        run: |
          gh pr create \
          --base develop \
          --head ${{ env.RELEASE_BRANCH }} \
          --title ":rocket: ${{ env.RELEASE_VERSION}}" \
          --repo kong/insomnia \
          --body "**Automated pull request**"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}

  trigger-release-build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: [start-release]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          repository: kong/insomnia
          persist-credentials: false

      - name: Configure Git user
        id: configure_git_user
        uses: Homebrew/actions/git-user-config@266845213695c3047d210b2e8fbc42ecdaf45802 # master
        with:
          username: insomnia-infra

      - name: Git Commit
        run: git commit -am "Trigger release/${{ env.RELEASE_VERSION}} build" --allow-empty

      - name: Git Push changes
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/kong/insomnia.git"
          git push "${remote_repo}" --follow-tags
        env:
          GITHUB_ACTOR: insomnia-infra
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}

      # NOTE: Approve the PR with jay.wu@konghq.com's token
      - name: Approve Pull Request
        run: |
          gh pr review ${{ env.RELEASE_BRANCH }} --approve --repo kong/insomnia
        env:
          GITHUB_TOKEN: ${{ secrets.CE_PR_APPROVE_TOKEN }}
