name: Prettier Autoformat

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: |
          npx -y prettier --write .

      - name: Commit formatted code
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-format with Prettier"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi
