name: Snapcraft Test

on:
  push:
    branches:
      - release/snap

jobs:
  Core:
    runs-on: ubuntu-latest
    container: electronuserland/builder:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm run bootstrap
      - run: npm run app-release
        env:
          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
          BUILD_TARGETS: AppImage,deb,tar.gz,rpm,snap
          GITHUB_REF: core@2020.2.2
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          NPM_CONFIG_TARGET: 3.1.13
          NPM_CONFIG_DISTURL: https://electronjs.org/headers
          NPM_CONFIG_RUNTIME: electron
  Designer:
    runs-on: ubuntu-latest
    container: electronuserland/builder:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm run bootstrap
      - run: npm run app-release
        env:
          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
          BUILD_TARGETS: AppImage,deb,tar.gz,rpm,snap
          GITHUB_REF: designer@2020.2.2
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          NPM_CONFIG_TARGET: 3.1.13
          NPM_CONFIG_DISTURL: https://electronjs.org/headers
          NPM_CONFIG_RUNTIME: electron
