name: Release Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version of the release (e.g. 2022.1.0 or 2022.1.0-beta.0)
      run_id:
        required: true
        description: Run id of the release-core-build workflow


env:
  RELEASE_VERSION: ${{ github.event.inputs.version }}
  RELEASE_CORE_TAG: core/${{ github.event.inputs.version }}
  RELEASE_BRANCH: release/${{ github.event.inputs.version }}
  RUN_ID: ${{ github.event.inputs.run_id }}
  IS_PRERELEASE: ${{ contains(github.event.inputs.version, 'alpha') || contains(github.event.inputs.version, 'beta') }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch # Check out the release branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_BRANCH }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: release-core-build.yml
          workflow_conclusion: success
          # branch: ${{ env.RELEASE_BRANCH }} # Branch workflow ran on != branch the workflow created
          run_id: ${{ env.RUN_ID }}
          path: ./artifacts/

      - name: Create Tag and Release
        uses: avakar/tag-and-release@v1
        id: core_tag_and_release
        with:
          tag_name: ${{ env.RELEASE_CORE_TAG }}
          release_name: Insomnia ${{ env.RELEASE_VERSION }}
          prerelease: ${{ env.IS_PRERELEASE }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.core_tag_and_release.outputs.id }}
          tag_name: ${{ env.RELEASE_CORE_TAG }}
          file: "./artifacts/*-latest-artifacts/insomnia-app/**"
          prerelease: ${{ env.IS_PRERELEASE }}
          draft: true

      # - name: Create github release for Inso lib@ tag
      # - name: Upload Inso artifacts to release
      # - name: Publish npm packages
      # - name: Publish to pulp if stable
      # - name: If stable, upload to snapcraft
      # - name: Publish beta/stable to Insomnia API
      # - name: Check if branch is mergeable
      # - name: Merge Git branch


