name: Release Fedora

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Release version (e.g. 2022.1.0 or 2022.1.0-beta.0)

env:
  RELEASE_CORE_TAG: core@${{ github.event.inputs.version }}
  IS_PRERELEASE: ${{ contains(github.event.inputs.version, 'alpha') || contains(github.event.inputs.version, 'beta') }}

jobs:
  release-fedora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch # Check out the release branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_CORE_TAG }}
          fetch-depth: 0
          persist-credentials: false

      - name: Build Insomnia from sources for Fedora
        run: |
          docker build --tag fedora-insomnia-builder:latest -f fedora.Dockerfile .
          docker create --name builder fedora-insomnia-builder:latest
          docker cp builder:/insomnia/packages/insomnia/dist/. ./artifacts/
          docker rm -f builder

      - name: Upload artifacts to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.publish.outputs.release_id }}
          tag_name: ${{ env.RELEASE_CORE_TAG }}
          file: "./artifacts/**.rpm"
          prerelease: ${{ env.IS_PRERELEASE }}
          draft: false
