name: Snapcraft Test

on:
  push:
    branches:
      - release/snap

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  NPM_CONFIG_TARGET: 3.1.13
  NPM_CONFIG_DISTURL: https://electronjs.org/headers
  NPM_CONFIG_RUNTIME: electron

jobs:
  Core:
    runs-on: ubuntu-latest
    container: electronuserland/builder:latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install snapcraft
      - run: npm run bootstrap
      - run: npm run app-release
        env:
          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
          BUILD_TARGETS: snap
          GIT_TAG: core@2020.2.2
  Designer:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install snapcraft
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm run bootstrap
      - run: npm run app-release
        env:
          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
          BUILD_TARGETS: snap
          GIT_TAG: designer@2020.2.2
