name: SAST

on:
  pull_request: {}
  push:
    branches:
    - develop
    - release/*
  workflow_dispatch: {}


jobs:
  semgrep:
    timeout-minutes: 5
    name: Semgrep SAST
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - uses: Kong/public-shared-actions/security-actions/semgrep@28d20a1f492927f35b00b317acd78f669c45f88b # v2.7.3
