name: e2e App Tests

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  Test:
    timeout-minutes: 40
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kong'

      - name: Install packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Build app for smoke tests
        run: NODE_OPTIONS='--max_old_space_size=6144' npm run app-build

      - name: Smoke test electron app
        run: npm run test:build -w packages/insomnia-smoke-test -- --project=Smoke

      - name: Upload smoke test
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          if-no-files-found: ignore
          name: ubuntu-smoke-test-traces-${{ github.run_number }}
          path: packages/insomnia-smoke-test/traces
