name: WJ Tests of Insomnia App

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - wj-test
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    timeout-minutes: 40
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kong'

      - name: Install packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build app for tests
        run: NODE_OPTIONS='--max_old_space_size=6144' npm run app-build

      - name: WJ test electron app
        run: npm run test:build -w wj-test -- --project=WJTest

      - name: Upload test traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          if-no-files-found: ignore
          name: ubuntu-wj-test-traces-${{ github.run_number }}
          path: packages/wj-test/traces

      - name: Report - Prepare report for Pages
        id: prepare_report
        if: ${{ !cancelled() }}
        run: |
          mkdir -p gh-pages
          cp -r packages/wj-test/report/* gh-pages/
          echo "Content in gh-pages："
          ls -la gh-pages

      - name: Report - Configure Github Pages
        id: configure_pages
        if: ${{ !cancelled() }}
        uses: actions/configure-pages@v5
        with:
          # Auto-enable Pages if it's not already enabled (requires proper permissions)
          enablement: true # Critical addition to fix "Not Found" error

      - name: Report - Upload report to Pages artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Report - Upload HTML test report for download
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ubuntu-wj-test-report-${{ github.run_number }}
          path: 'gh-pages'

      - name: Report - Deploy to GitHub Pages
        if: ${{ !cancelled() }}
        id: deployment
        uses: actions/deploy-pages@v4
